# auto-generated by comopy
from __future__ import annotations
import cocotb
from cocotb.triggers import Timer
from cocotb_tools.runner import get_runner
import os
import sys
from pathlib import Path

@cocotb.test()
async def test_Popcount255(dut):
    await Timer(1, units='step')

    vectors = [
        (0, 0),
        (1, 1),
        (255, 8),
        (170, 4),
    ]

    for vec in vectors:
        dut.in_.value = vec[0]
        await Timer(1, units='step')
        assert dut.out.value == vec[1]


def test_Popcount255_runner():
    """Pytest entry point using cocotb-tools runner"""
    hdl_toplevel_lang = os.getenv("HDL_TOPLEVEL_LANG", "verilog")
    sim = os.getenv("SIM", "icarus")
    proj_path = Path(__file__).resolve().parent

    if hdl_toplevel_lang == "verilog":
        sources = [proj_path / "Popcount255.sv"]
    else:
        sources = [proj_path / "Popcount255.vhdl"]

    # 将当前路径加入搜索路径，确保 cocotb 能找到测试模块
    sys.path.append(str(proj_path))

    runner = get_runner(sim)
    runner.build(
        sources=sources,
        hdl_toplevel="Popcount255",
        always=True,
    )
    runner.test(
        hdl_toplevel="Popcount255", 
        test_module=f"test_Popcount255_auto"
    )

if __name__ == "__main__":
    test_Popcount255_runner()
