# auto-generated by comopy
from __future__ import annotations
import cocotb
from cocotb.triggers import Timer
from cocotb_tools.runner import get_runner
import os
import sys
from pathlib import Path

@cocotb.test()
async def test_Conditional(dut):
    await Timer(1, units='step')

    vectors = [
        (18, 52, 86, 120, 18),
        (52, 18, 86, 120, 18),
        (86, 52, 18, 120, 18),
        (120, 52, 86, 18, 18),
    ]

    for vec in vectors:
        dut.a.value = vec[0]
        dut.b.value = vec[1]
        dut.c.value = vec[2]
        dut.d.value = vec[3]
        await Timer(1, units='step')
        assert dut.min.value == vec[4]


def test_Conditional_runner():
    """Pytest entry point using cocotb-tools runner"""
    hdl_toplevel_lang = os.getenv("HDL_TOPLEVEL_LANG", "verilog")
    sim = os.getenv("SIM", "icarus")
    proj_path = Path(__file__).resolve().parent

    if hdl_toplevel_lang == "verilog":
        sources = [proj_path / "Conditional.sv"]
    else:
        sources = [proj_path / "Conditional.vhdl"]

    # 将当前路径加入搜索路径，确保 cocotb 能找到测试模块
    sys.path.append(str(proj_path))

    runner = get_runner(sim)
    runner.build(
        sources=sources,
        hdl_toplevel="Conditional",
        always=True,
    )
    runner.test(
        hdl_toplevel="Conditional", 
        test_module=f"test_Conditional_auto"
    )

if __name__ == "__main__":
    test_Conditional_runner()
