# auto-generated by comopy
import cocotb
from cocotb.triggers import Timer

@cocotb.test()
async def test_Reduction(dut):
    await Timer(1, units='ns')

    vectors = [
        (0, 0),
        (1, 1),
        (15, 0),
        (255, 0),
        (171, 1),
    ]

    for vec in vectors:
        dut.in_.value = vec[0]
        await Timer(1, units='ns')
        assert dut.parity.value == vec[1]