# auto-generated by comopy
from __future__ import annotations
import cocotb
from cocotb.triggers import Timer
from cocotb_tools.runner import get_runner
import os
import sys
from pathlib import Path

@cocotb.test()
async def test_Wire4(dut):
    await Timer(1, units='step')

    vectors = [
        (1, 0, 1, 1, 0, 0, 1),
        (0, 1, 0, 0, 1, 1, 0),
    ]

    for vec in vectors:
        dut.a.value = vec[0]
        dut.b.value = vec[1]
        dut.c.value = vec[2]
        await Timer(1, units='step')
        assert dut.w.value == vec[3]
        assert dut.x.value == vec[4]
        assert dut.y.value == vec[5]
        assert dut.z.value == vec[6]


def test_Wire4_runner():
    """Pytest entry point using cocotb-tools runner"""
    hdl_toplevel_lang = os.getenv("HDL_TOPLEVEL_LANG", "verilog")
    sim = os.getenv("SIM", "icarus")
    proj_path = Path(__file__).resolve().parent

    if hdl_toplevel_lang == "verilog":
        sources = [proj_path / "Wire4.sv"]
    else:
        sources = [proj_path / "Wire4.vhdl"]

    # 将当前路径加入搜索路径，确保 cocotb 能找到测试模块
    sys.path.append(str(proj_path))

    runner = get_runner(sim)
    runner.build(
        sources=sources,
        hdl_toplevel="Wire4",
        always=True,
    )
    runner.test(
        hdl_toplevel="Wire4", 
        test_module=f"test_Wire4_auto"
    )

if __name__ == "__main__":
    test_Wire4_runner()
