# auto-generated by comopy
from __future__ import annotations
import cocotb
from cocotb.triggers import Timer
from cocotb_tools.runner import get_runner
import os
import sys
from pathlib import Path


@cocotb.test()
async def test_Andgate(dut):
    await Timer(1)

    vectors = [
        (0, 0, 0),
        (1, 0, 0),
        (0, 1, 0),
        (1, 1, 1),
    ]
    
    for vec in vectors:
        dut.a.value = vec[0]
        dut.b.value = vec[1]
        await Timer(1)
        assert dut.out.value == vec[2]
        


def test_Andgate_runner():
    """Pytest entry point using cocotb-tools runner"""
    hdl_toplevel_lang = os.getenv("HDL_TOPLEVEL_LANG", "verilog")
    sim = os.getenv("SIM", "icarus")
    proj_path = Path(__file__).resolve().parent
    build_test_args = []
    if hdl_toplevel_lang == "verilog":
        sources = [proj_path / "Andgate.sv"]
    if hdl_toplevel_lang == "vhdl" and sim == "xcelium":
        build_test_args = ["-v93"]


    # 将当前路径加入搜索路径，确保 cocotb 能找到测试模块
    sys.path.append(str(proj_path))

    runner = get_runner(sim)
    runner.build(
        sources=sources,
        hdl_toplevel="Andgate",
        always=True,
        build_args=build_test_args,
    )
    runner.test(
        hdl_toplevel="Andgate", 
        test_module=f"test_Andgate_auto", test_args=build_test_args
    )

if __name__ == "__main__":
    test_Andgate_runner()
